/**
 * @file    mspm0g3507_gpio_cfg.c
 * @brief   MSPM0G3507 GPIO 板级配置，定义虚拟引脚与物理引脚映射。
 * @details 本文件属于 HAL 层公共代码，已补充快速上手导向注释。
 *          建议结合对应 cfg 文件与上层调用路径一起阅读。
 */
#include "hc_hal_gpio.h"
#include "ti_msp_dl_config.h"

const HC_GPIO_PinCfg_t g_gpioPinMap[VPIN_MAX] = {
    [VPIN_K1] = {
        .port = (HC_VOID *)GPIO_GRP_KEY_K1_PORT,
        .pin = GPIO_GRP_KEY_K1_PIN,
        .iomux = GPIO_GRP_KEY_K1_IOMUX,
        .dir = HC_GPIO_DIR_INPUT,
        .pull = HC_GPIO_PULL_UP,
        .ioStruct = HC_GPIO_IO_PP,
        .initState = HC_FALSE,
        .irqMode = HC_GPIO_IRQ_FALLING,
    },
    [VPIN_K2] = {
        .port = (HC_VOID *)GPIO_GRP_KEY_K2_PORT,
        .pin = GPIO_GRP_KEY_K2_PIN,
        .iomux = GPIO_GRP_KEY_K2_IOMUX,
        .dir = HC_GPIO_DIR_INPUT,
        .pull = HC_GPIO_PULL_UP,
        .ioStruct = HC_GPIO_IO_PP,
        .initState = HC_FALSE,
        .irqMode = HC_GPIO_IRQ_FALLING,
    },
    [VPIN_K3] = {
        .port = (HC_VOID *)GPIO_GRP_KEY_K3_PORT,
        .pin = GPIO_GRP_KEY_K3_PIN,
        .iomux = GPIO_GRP_KEY_K3_IOMUX,
        .dir = HC_GPIO_DIR_INPUT,
        .pull = HC_GPIO_PULL_UP,
        .ioStruct = HC_GPIO_IO_PP,
        .initState = HC_FALSE,
        .irqMode = HC_GPIO_IRQ_FALLING,
    },
    [VPIN_K4] = {
        .port = (HC_VOID *)GPIO_GRP_KEY_K4_PORT,
        .pin = GPIO_GRP_KEY_K4_PIN,
        .iomux = GPIO_GRP_KEY_K4_IOMUX,
        .dir = HC_GPIO_DIR_INPUT,
        .pull = HC_GPIO_PULL_UP,
        .ioStruct = HC_GPIO_IO_PP,
        .initState = HC_FALSE,
        .irqMode = HC_GPIO_IRQ_FALLING,
    },
    [VPIN_MOTOR_L1] = {
        .port = (HC_VOID *)GPIO_GRP_MOTOR_PORT,
        .pin = GPIO_GRP_MOTOR_BIN1_PIN,
        .iomux = GPIO_GRP_MOTOR_BIN1_IOMUX,
        .dir = HC_GPIO_DIR_OUTPUT,
        .pull = HC_GPIO_PULL_NONE,
        .ioStruct = HC_GPIO_IO_PP,
        .initState = HC_FALSE,
        .irqMode = HC_GPIO_IRQ_NONE,
    },
    [VPIN_MOTOR_L2] = {
        .port = (HC_VOID *)GPIO_GRP_MOTOR_PORT,
        .pin = GPIO_GRP_MOTOR_BIN2_PIN,
        .iomux = GPIO_GRP_MOTOR_BIN2_IOMUX,
        .dir = HC_GPIO_DIR_OUTPUT,
        .pull = HC_GPIO_PULL_NONE,
        .ioStruct = HC_GPIO_IO_PP,
        .initState = HC_FALSE,
        .irqMode = HC_GPIO_IRQ_NONE,
    },
    [VPIN_MOTOR_R1] = {
        .port = (HC_VOID *)GPIO_GRP_MOTOR_PORT,
        .pin = GPIO_GRP_MOTOR_AIN1_PIN,
        .iomux = GPIO_GRP_MOTOR_AIN1_IOMUX,
        .dir = HC_GPIO_DIR_OUTPUT,
        .pull = HC_GPIO_PULL_NONE,
        .ioStruct = HC_GPIO_IO_PP,
        .initState = HC_FALSE,
        .irqMode = HC_GPIO_IRQ_NONE,
    },
    [VPIN_MOTOR_R2] = {
        .port = (HC_VOID *)GPIO_GRP_MOTOR_PORT,
        .pin = GPIO_GRP_MOTOR_AIN2_PIN,
        .iomux = GPIO_GRP_MOTOR_AIN2_IOMUX,
        .dir = HC_GPIO_DIR_OUTPUT,
        .pull = HC_GPIO_PULL_NONE,
        .ioStruct = HC_GPIO_IO_PP,
        .initState = HC_FALSE,
        .irqMode = HC_GPIO_IRQ_NONE,
    },
    [VPIN_COUNT_L1] = {
        .port = (HC_VOID *)GPIO_GRP_MOTOR_INTERRUPT_PIN_L_A_PORT,
        .pin = GPIO_GRP_MOTOR_INTERRUPT_PIN_L_A_PIN,
        .iomux = GPIO_GRP_MOTOR_INTERRUPT_PIN_L_A_IOMUX,
        .dir = HC_GPIO_DIR_INPUT,
        .pull = HC_GPIO_PULL_NONE,
        .ioStruct = HC_GPIO_IO_PP,
        .initState = HC_FALSE,
        .irqMode = HC_GPIO_IRQ_BOTH,
    },
    [VPIN_COUNT_L2] = {
        .port = (HC_VOID *)GPIO_GRP_MOTOR_INTERRUPT_PIN_L_B_PORT,
        .pin = GPIO_GRP_MOTOR_INTERRUPT_PIN_L_B_PIN,
        .iomux = GPIO_GRP_MOTOR_INTERRUPT_PIN_L_B_IOMUX,
        .dir = HC_GPIO_DIR_INPUT,
        .pull = HC_GPIO_PULL_NONE,
        .ioStruct = HC_GPIO_IO_PP,
        .initState = HC_FALSE,
        .irqMode = HC_GPIO_IRQ_BOTH,
    },
    [VPIN_COUNT_R1] = {
        .port = (HC_VOID *)GPIO_GRP_MOTOR_INTERRUPT_PIN_R_A_PORT,
        .pin = GPIO_GRP_MOTOR_INTERRUPT_PIN_R_A_PIN,
        .iomux = GPIO_GRP_MOTOR_INTERRUPT_PIN_R_A_IOMUX,
        .dir = HC_GPIO_DIR_INPUT,
        .pull = HC_GPIO_PULL_NONE,
        .ioStruct = HC_GPIO_IO_PP,
        .initState = HC_FALSE,
        .irqMode = HC_GPIO_IRQ_BOTH,
    },
    [VPIN_COUNT_R2] = {
        .port = (HC_VOID *)GPIO_GRP_MOTOR_INTERRUPT_PIN_R_B_PORT,
        .pin = GPIO_GRP_MOTOR_INTERRUPT_PIN_R_B_PIN,
        .iomux = GPIO_GRP_MOTOR_INTERRUPT_PIN_R_B_IOMUX,
        .dir = HC_GPIO_DIR_INPUT,
        .pull = HC_GPIO_PULL_NONE,
        .ioStruct = HC_GPIO_IO_PP,
        .initState = HC_FALSE,
        .irqMode = HC_GPIO_IRQ_BOTH,
    },
    [VPIN_GRAY_0] = {
        .port = (HC_VOID *)GPIO_GRP_GRAYSCALE_PORT,
        .pin = GPIO_GRP_GRAYSCALE_PIN_IN1_PIN,
        .iomux = GPIO_GRP_GRAYSCALE_PIN_IN1_IOMUX,
        .dir = HC_GPIO_DIR_INPUT,
        .pull = HC_GPIO_PULL_NONE,
        .ioStruct = HC_GPIO_IO_PP,
        .initState = HC_FALSE,
        .irqMode = HC_GPIO_IRQ_NONE,
    },
    [VPIN_GRAY_1] = {
        .port = (HC_VOID *)GPIO_GRP_GRAYSCALE_PORT,
        .pin = GPIO_GRP_GRAYSCALE_PIN_IN2_PIN,
        .iomux = GPIO_GRP_GRAYSCALE_PIN_IN2_IOMUX,
        .dir = HC_GPIO_DIR_INPUT,
        .pull = HC_GPIO_PULL_NONE,
        .ioStruct = HC_GPIO_IO_PP,
        .initState = HC_FALSE,
        .irqMode = HC_GPIO_IRQ_NONE,
    },
    [VPIN_GRAY_2] = {
        .port = (HC_VOID *)GPIO_GRP_GRAYSCALE_PORT,
        .pin = GPIO_GRP_GRAYSCALE_PIN_IN3_PIN,
        .iomux = GPIO_GRP_GRAYSCALE_PIN_IN3_IOMUX,
        .dir = HC_GPIO_DIR_INPUT,
        .pull = HC_GPIO_PULL_NONE,
        .ioStruct = HC_GPIO_IO_PP,
        .initState = HC_FALSE,
        .irqMode = HC_GPIO_IRQ_NONE,
    },
    [VPIN_GRAY_3] = {
        .port = (HC_VOID *)GPIO_GRP_GRAYSCALE_PORT,
        .pin = GPIO_GRP_GRAYSCALE_PIN_IN4_PIN,
        .iomux = GPIO_GRP_GRAYSCALE_PIN_IN4_IOMUX,
        .dir = HC_GPIO_DIR_INPUT,
        .pull = HC_GPIO_PULL_NONE,
        .ioStruct = HC_GPIO_IO_PP,
        .initState = HC_FALSE,
        .irqMode = HC_GPIO_IRQ_NONE,
    },
    [VPIN_GRAY_4] = {
        .port = (HC_VOID *)GPIO_GRP_GRAYSCALE_PORT,
        .pin = GPIO_GRP_GRAYSCALE_PIN_IN5_PIN,
        .iomux = GPIO_GRP_GRAYSCALE_PIN_IN5_IOMUX,
        .dir = HC_GPIO_DIR_INPUT,
        .pull = HC_GPIO_PULL_NONE,
        .ioStruct = HC_GPIO_IO_PP,
        .initState = HC_FALSE,
        .irqMode = HC_GPIO_IRQ_NONE,
    },
    [VPIN_GRAY_5] = {
        .port = (HC_VOID *)GPIO_GRP_GRAYSCALE_PORT,
        .pin = GPIO_GRP_GRAYSCALE_PIN_IN6_PIN,
        .iomux = GPIO_GRP_GRAYSCALE_PIN_IN6_IOMUX,
        .dir = HC_GPIO_DIR_INPUT,
        .pull = HC_GPIO_PULL_NONE,
        .ioStruct = HC_GPIO_IO_PP,
        .initState = HC_FALSE,
        .irqMode = HC_GPIO_IRQ_NONE,
    },
    [VPIN_GRAY_6] = {
        .port = (HC_VOID *)GPIO_GRP_GRAYSCALE_PORT,
        .pin = GPIO_GRP_GRAYSCALE_PIN_IN7_PIN,
        .iomux = GPIO_GRP_GRAYSCALE_PIN_IN7_IOMUX,
        .dir = HC_GPIO_DIR_INPUT,
        .pull = HC_GPIO_PULL_NONE,
        .ioStruct = HC_GPIO_IO_PP,
        .initState = HC_FALSE,
        .irqMode = HC_GPIO_IRQ_NONE,
    },
    [VPIN_GRAY_7] = {
        .port = (HC_VOID *)GPIO_GRP_GRAYSCALE_PORT,
        .pin = GPIO_GRP_GRAYSCALE_PIN_IN8_PIN,
        .iomux = GPIO_GRP_GRAYSCALE_PIN_IN8_IOMUX,
        .dir = HC_GPIO_DIR_INPUT,
        .pull = HC_GPIO_PULL_NONE,
        .ioStruct = HC_GPIO_IO_PP,
        .initState = HC_FALSE,
        .irqMode = HC_GPIO_IRQ_NONE,
    },
};
