#include "hc_hal_gpio.h"
#include "main.h"

const HC_GPIO_PinCfg_t g_gpioPinMap[VPIN_MAX] = {
    [VPIN_K1] = {
        .port = (HC_VOID *)KEY0_GPIO_Port,
        .pin = KEY0_Pin,
        .iomux = 0u,
        .dir = HC_GPIO_DIR_INPUT,
        /* 当前 2 键菜单按“低电平按下”建模。
         * 这里显式打开上拉，避免按键悬空导致：
         * 1. MultiButton 读值漂移；
         * 2. 边沿中断无法稳定触发；
         * 3. 菜单偶发不响应或乱跳。 */
        .pull = HC_GPIO_PULL_UP,
        .ioStruct = HC_GPIO_IO_PP,
        .initState = HC_FALSE,
        .irqMode = HC_GPIO_IRQ_BOTH,
    },
    [VPIN_K2] = {
        .port = (HC_VOID *)KEY1_GPIO_Port,
        .pin = KEY1_Pin,
        .iomux = 0u,
        .dir = HC_GPIO_DIR_INPUT,
        .pull = HC_GPIO_PULL_UP,
        .ioStruct = HC_GPIO_IO_PP,
        .initState = HC_FALSE,
        .irqMode = HC_GPIO_IRQ_BOTH,
    },
    [VPIN_MOTOR_L1] = {
        .port = (HC_VOID *)M1_DIR_GPIO_Port,
        .pin = M1_DIR_Pin,
        .iomux = 0u,
        .dir = HC_GPIO_DIR_OUTPUT,
        .pull = HC_GPIO_PULL_NONE,
        .ioStruct = HC_GPIO_IO_PP,
        .initState = HC_FALSE,
        .irqMode = HC_GPIO_IRQ_NONE,
    },
    [VPIN_MOTOR_L2] = {
        .port = (HC_VOID *)M1_SLEEP_N_GPIO_Port,
        .pin = M1_SLEEP_N_Pin,
        .iomux = 0u,
        .dir = HC_GPIO_DIR_OUTPUT,
        .pull = HC_GPIO_PULL_NONE,
        .ioStruct = HC_GPIO_IO_PP,
        .initState = HC_FALSE,
        .irqMode = HC_GPIO_IRQ_NONE,
    },
    [VPIN_MOTOR_R1] = {
        .port = (HC_VOID *)M2_DIR_GPIO_Port,
        .pin = M2_DIR_Pin,
        .iomux = 0u,
        .dir = HC_GPIO_DIR_OUTPUT,
        .pull = HC_GPIO_PULL_NONE,
        .ioStruct = HC_GPIO_IO_PP,
        .initState = HC_FALSE,
        .irqMode = HC_GPIO_IRQ_NONE,
    },
    [VPIN_MOTOR_R2] = {
        .port = (HC_VOID *)M2_SLEEP_N_GPIO_Port,
        .pin = M2_SLEEP_N_Pin,
        .iomux = 0u,
        .dir = HC_GPIO_DIR_OUTPUT,
        .pull = HC_GPIO_PULL_NONE,
        .ioStruct = HC_GPIO_IO_PP,
        .initState = HC_FALSE,
        .irqMode = HC_GPIO_IRQ_NONE,
    },
    [VPIN_COUNT_L1] = {
        .port = (HC_VOID *)M1_ENC_A_GPIO_Port,
        .pin = M1_ENC_A_Pin,
        .iomux = 0u,
        .dir = HC_GPIO_DIR_INPUT,
        .pull = HC_GPIO_PULL_NONE,
        .ioStruct = HC_GPIO_IO_PP,
        .initState = HC_FALSE,
        .irqMode = HC_GPIO_IRQ_NONE,
    },
    [VPIN_COUNT_L2] = {
        .port = (HC_VOID *)M1_ENC_B_GPIO_Port,
        .pin = M1_ENC_B_Pin,
        .iomux = 0u,
        .dir = HC_GPIO_DIR_INPUT,
        .pull = HC_GPIO_PULL_NONE,
        .ioStruct = HC_GPIO_IO_PP,
        .initState = HC_FALSE,
        .irqMode = HC_GPIO_IRQ_NONE,
    },
    [VPIN_COUNT_R1] = {
        .port = (HC_VOID *)M2_ENC_A_GPIO_Port,
        .pin = M2_ENC_A_Pin,
        .iomux = 0u,
        .dir = HC_GPIO_DIR_INPUT,
        .pull = HC_GPIO_PULL_NONE,
        .ioStruct = HC_GPIO_IO_PP,
        .initState = HC_FALSE,
        .irqMode = HC_GPIO_IRQ_NONE,
    },
    [VPIN_COUNT_R2] = {
        .port = (HC_VOID *)M2_ENC_B_GPIO_Port,
        .pin = M2_ENC_B_Pin,
        .iomux = 0u,
        .dir = HC_GPIO_DIR_INPUT,
        .pull = HC_GPIO_PULL_NONE,
        .ioStruct = HC_GPIO_IO_PP,
        .initState = HC_FALSE,
        .irqMode = HC_GPIO_IRQ_NONE,
    },
};
